# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()

src = Glob('GD32VF103_standard_peripheral/Source/*.c')
src += Glob('n200/env_Eclipse/*.c')
src += Glob('n200/stubs/*.c')
src += ['GD32VF103_standard_peripheral/system_gd32vf103.c',
        'n200/drivers/n200_func.c',
        'n200/env_Eclipse/start.S',
        'n200/env_Eclipse/entry.S']

CPPPATH = [ cwd + '/GD32VF103_standard_peripheral/Include',
            cwd + '/GD32VF103_standard_peripheral',
            cwd + '/n200/drivers',
            cwd + '/n200/stubs']

CPPDEFINES = []

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
